# Generated by Django 6.0.4 on 2026-04-28 11:38

import re

from django.db import migrations, models


def populate_usernames(apps, schema_editor):
    User = apps.get_model("users", "User")
    for u in User.objects.all():
        if u.username:
            continue
        em = (u.email or "") or f"user{u.pk}@local"
        local = em.split("@")[0].strip() or f"user{u.pk}"
        base = re.sub(r"[^\w\-.]", "_", local)[:100].strip("_") or f"user{u.pk}"
        candidate = base
        n = 0
        while User.objects.filter(username=candidate).exclude(pk=u.pk).exists():
            n += 1
            candidate = f"{base}{n}"
        u.username = candidate.lower()
        u.save(update_fields=["username"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_donation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.RunPython(populate_usernames, noop_reverse),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
