# Generated by Django 6.0.4 on 2026-05-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_email_constraint_username_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('fund_owner', 'Fund owner'), ('donor', 'Donor')], db_index=True, max_length=32),
        ),
    ]
