# Generated by Django 6.0.4 on 2026-05-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_organization_address_organization_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
