# Generated by Django 6.0.4 on 2026-05-08 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_email_constraint_username_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goal_amount', models.PositiveBigIntegerField()),
                ('raised_amount', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('environment', 'Environment'), ('community', 'Community'), ('emergency', 'Emergency'), ('animals', 'Animals'), ('other', 'Other')], db_index=True, max_length=32)),
                ('country', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
                ('cover_image', models.ImageField(upload_to='funds/covers/%Y/%m/')),
                ('supporting_document', models.FileField(upload_to='funds/documents/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=32)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_funds', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='users.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'status'], name='funds_fund_organiz_865d66_idx')],
            },
        ),
    ]
